# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='app_vd_mod',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='c_LSR',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='c_LSR_unit',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='dfgc',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='dfgc_unit',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='dfgc_x',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='dfgc_y',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='dfgc_z',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='dfs_unit',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='eb_v',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='sig_v_unit',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='sp_lg_tc',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='sp_lg_th',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='sp_mu_V_unit',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='sp_r_c_unit',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='sp_r_h_unit',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='sp_rho_0_unit',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='sp_t_unit',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='spt',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='v_hb',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='v_r_err',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='v_r_unit',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='v_t',
        ),
        migrations.AlterField(
            model_name='observation',
            name='dec',
            field=models.FloatField(blank=True, null=True, verbose_name='Declinations [degree]'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='dfs',
            field=models.FloatField(blank=True, null=True, verbose_name='Distance from the sun [kpc]'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='gallat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude [degree]'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='gallon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude [degree]'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='ra',
            field=models.FloatField(blank=True, null=True, verbose_name='Right ascension [degree]'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='sig_err',
            field=models.FloatField(blank=True, null=True, verbose_name='Observational uncertainty [km/s]'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='sig_v',
            field=models.FloatField(blank=True, null=True, verbose_name='Velocity dispersion [km/s]'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='v_r',
            field=models.FloatField(blank=True, null=True, verbose_name='Heliocentric radial velocity [km/s]'),
        ),
    ]
